version: '3.4'

services:
  amivulnerable_db:
    container_name: MySqlDbAmIVulnerable
    image: mysql:8.0.2
    environment:
      - MYSQL_ROOT_PASSWORD=cvecve
      - MYSQL_DATABASE=cve
      - MYSQL_USER=u
      - MYSQL_PASSWORD=p
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_volume:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  amivulnerable:
    container_name: ApiAmIVulnerable
    build:
      context: .
      dockerfile: AmIVulnerable/Dockerfile
    # ports:
    #   - 8080:80
    #   - 8443:443
    depends_on:
      - amivulnerable_db

volumes:
  db_volume:
