version: '3.4'

networks:
  amivulnerable:

services:
  amivulnerable:
    networks:
      - amivulnerable
    container_name: api
    image: amivulnerable:latest
    build:
      context: .
      dockerfile: AmIVulnerable/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
