@startuml "Simultanius search on LiteDb-Files"

    start
    while (foreach product in list to search)
        if (runCounter < fillPipe) then (yes)
            :Case A\n"fill the pipe";
        elseif (runCounter < (absoluteCounter - fillPipe)) then (yes)
            :Case B\n"run the pipe";
        else (no)
            :Fall C\n"drain the pipe";
            :Case result-list;
            stop
        endif
    endwhile
    end

@enduml
